package com.integral.system.message.bean;

// Generated Jan 11, 2012 5:50:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SystemMessage generated by hbm2java
 */
public class SystemMessage implements java.io.Serializable {

    private String messageId;

    private String messageFrom;

    private String messageTo;

    private Date messageSendTime;

    private Date messageReceiveTime;

    private String messageNew;

    private String messageContent;

    private String messageTitle;

    public SystemMessage() {
    }

    public SystemMessage(String messageId) {
        this.messageId = messageId;
    }

    public SystemMessage(String messageId, String messageFrom, String messageTo, Date messageSendTime,
            Date messageReceiveTime, String messageNew, String messageContent, String messageTitle) {
        this.messageId = messageId;
        this.messageFrom = messageFrom;
        this.messageTo = messageTo;
        this.messageSendTime = messageSendTime;
        this.messageReceiveTime = messageReceiveTime;
        this.messageNew = messageNew;
        this.messageContent = messageContent;
        this.messageTitle = messageTitle;
    }

    public String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getMessageFrom() {
        return this.messageFrom;
    }

    public void setMessageFrom(String messageFrom) {
        this.messageFrom = messageFrom;
    }

    public String getMessageTo() {
        return this.messageTo;
    }

    public void setMessageTo(String messageTo) {
        this.messageTo = messageTo;
    }

    public Date getMessageSendTime() {
        return this.messageSendTime;
    }

    public void setMessageSendTime(Date messageSendTime) {
        this.messageSendTime = messageSendTime;
    }

    public Date getMessageReceiveTime() {
        return this.messageReceiveTime;
    }

    public void setMessageReceiveTime(Date messageReceiveTime) {
        this.messageReceiveTime = messageReceiveTime;
    }

    public String getMessageNew() {
        return this.messageNew;
    }

    public void setMessageNew(String messageNew) {
        this.messageNew = messageNew;
    }

    public String getMessageContent() {
        return this.messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getMessageTitle() {
        return this.messageTitle;
    }

    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

}
