package com.integral.family.relationship.bean;

// Generated Dec 13, 2011 1:16:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * FamilyRelation generated by hbm2java
 */
public class FamilyRelation implements java.io.Serializable {

    private String familyRelationId;

    private String familyRelation;

    private String familyRelationFrom;

    private String familyRelationTo;

    public FamilyRelation() {
    }

    public FamilyRelation(String familyRelationId) {
        this.familyRelationId = familyRelationId;
    }

    public FamilyRelation(String familyRelationId, String familyRelation, String familyRelationFrom,
            String familyRelationTo) {
        this.familyRelationId = familyRelationId;
        this.familyRelation = familyRelation;
        this.familyRelationFrom = familyRelationFrom;
        this.familyRelationTo = familyRelationTo;
    }

    public String getFamilyRelationId() {
        return this.familyRelationId;
    }

    public void setFamilyRelationId(String familyRelationId) {
        this.familyRelationId = familyRelationId;
    }

    public String getFamilyRelation() {
        return this.familyRelation;
    }

    public void setFamilyRelation(String familyRelation) {
        this.familyRelation = familyRelation;
    }

    public String getFamilyRelationFrom() {
        return this.familyRelationFrom;
    }

    public void setFamilyRelationFrom(String familyRelationFrom) {
        this.familyRelationFrom = familyRelationFrom;
    }

    public String getFamilyRelationTo() {
        return this.familyRelationTo;
    }

    public void setFamilyRelationTo(String familyRelationTo) {
        this.familyRelationTo = familyRelationTo;
    }

}
